### ISSUE TITLE
MGLAnnotation.Title and Subtitle are readonly

### ISSUE THREAD

**Issue by charlenni** [NAXAM/mapbox-ios-binding#1]
It isn't possible to set the title or subtitle of an annotation.

**Comment by fleuverouge** [comment]
Hi @charlenni , sorry for the late response.
In MGLAnnotation, these two properties are readonly: [Documentation](https://www.mapbox.com/ios-sdk/api/3.6.4/Protocols/MGLAnnotation.html#/c:objc(pl)MGLAnnotation(py)subtitle)
Please check their example to see how to add annotations: [Add a marker](https://www.mapbox.com/ios-sdk/examples/marker/)
