### ISSUE TITLE
Cannot set annotation tap

### ISSUE THREAD

**Issue by suhomlineugene** [NAXAM/mapbox-ios-binding#15]
I try to make annotation visible by tap, but when I tap marker annotation doesn't appears.

Here is my code from ViewController

`public partial class MapController : UIViewController
    {
        MGLMapView map;

        public MapController(IntPtr handle) : base(handle)
        {
        }
        public override async void ViewDidLoad()
        {
            //Getting list of tours
            List<Experience> experiences = await ExperienceMethods.GetExperiencesAsync();
            //Getting centrer location, for us it's 1 element in List
            double lat_center = Convert.ToDouble(experiences[0].lat, CultureInfo.InvariantCulture);
            double lng_center = Convert.ToDouble(experiences[0].lng, CultureInfo.InvariantCulture);

            //Rendering map
            MGLAccountManager.AccessToken = "************";
            map = new MGLMapView(
                View.Bounds,
                new NSUrl("mapbox://styles/mapbox/streets-v10")
                );
            map.SetCenterCoordinate(new CLLocationCoordinate2D(lat_center, lng_center), 11, false);
            View.AddSubview(map);
            //Here is delegate for tap
            map.WeakDelegate = this;

            //Getting all pointers via forloop
            for (int i =0; i < experiences.Count; i++)
            {

                double lat = Convert.ToDouble(experiences[i].lat, CultureInfo.InvariantCulture);
                double lng = Convert.ToDouble(experiences[i].lng, CultureInfo.InvariantCulture);
                var point = new MGLPointAnnotation()
                {
                    Title = experiences[i].title,
                    Coordinate = new CLLocationCoordinate2D(Convert.ToDouble(experiences[i].lat, CultureInfo.InvariantCulture), Convert.ToDouble(experiences[i].lng, CultureInfo.InvariantCulture))
                };
                map.AddAnnotation(point);

            }

        }
        [Export("map:annotationCanShowCallout:")]
        public bool MapView_AnnotationCanShowCallout(MGLMapView map, IMGLAnnotation annotation)
        {
            return true;
        }`

How I can fix this?

**Comment by tuyen-vuduc** [comment]
Closing old issue.
