### ISSUE TITLE
iOS designer crashes with VS 8.0 (build 3001)

### ISSUE THREAD

**Issue by fettergabor** [NAXAM/mapbox-ios-binding#16]
It is quite mysterious, but with the latest VS for Mac, iOS designer crashes if you open a xib or storyboard if the project uses this binding library. If I remove the library, xibs open correctly.

The issue applies to the example project here, so it is very easy to reproduce:
1. Open this example project with VS for Mac 8.0
2. Attempt to open iOS designer with e.g.: LaunchScreen.storyboard
Crashlog attached.
[crash.txt](https://github.com/NAXAM/mapbox-ios-binding/files/3038119/crash.txt)

**Comment by josephdonnelly** [comment]
I am having the same issue, were you able to resolve it @fettergabor ?

**Comment by fettergabor** [comment]
> I am having the same issue, were you able to resolve it @fettergabor ?

Unfortunately, the problem persists. :-( There were one or two minor VS updates, but no change.
We are open spend some time with fixing this but have no idea where to start. Do you have a hint?

**Comment by josephdonnelly** [comment]
No clue. It works if you create the view with code. I'm going forward that route instead

**Comment by fettergabor** [comment]
That route did not work for me. (Same crash.) This 3rd party must be removed from the project to fix iOS designer. Not convenient, but at least it works..

**Comment by josephdonnelly** [comment]
Switching to this binding works for me. It allows me to open storyboard assets and use Mapbox, and its available in Nuget.

https://github.com/alexrainman/MapboxXamarin

You'll have to change your code from `using Mapbox;` to`using MapboxBindings;`

**Comment by tuyen-vuduc** [comment]
Closing old issue
