### ISSUE TITLE
Mapbox outdated

### ISSUE THREAD

**Issue by raimondsL** [NAXAM/mapbox-ios-binding#18]
Mapbox 5.4 is outdated

**Comment by tuyen-vuduc** [comment]
Dear @raimondslinde,

We are looking for a sponsor/free hand from community to do the upgrade.

It's huge workload for each major version upgrade.

Cheers.

**Comment by fleuverouge** [comment]
Hi @raimondslinde ,
I've updated the binding for SDK v6.3.0, but not had time to test it throughout. If you're interested, you may find the new files in the branch [mapbox_sdk_6.3.0](https://github.com/NAXAM/mapbox-ios-binding/tree/mapbox_sdk_6.3.0)

**Comment by raimondsL** [comment]
Thank you for your hard work @fleuverouge ,
I can confirm that I can add 6.3 version and launch it w/o crashing.

@fleuverouge this Mapbox project is irreplaceable to our Outdoor hiking project, we love the max detailed MapStyle. We are currently facing a few issues:
1) adding Map Scale to the Map
2) User Location Direction (I haven't checked 6.3 because iPhone simulator doesn't provide a location)
3) Adding SymbolAnnotation.TextField to the Waypoints. (Text is not displayed).

Do you know if this can be fixed or we need to wait for Naxam.Mapbox.Forms update? This is my first project and it's created on Windows Visual Studio MVVM Xamarin.Forms.

Once again than you for your hard work.

**Comment by fleuverouge** [comment]
Hi @raimondslinde 
1. Can you please specify a use case of "Map Scale"? (would be great if there's an example in Obj C or Swift).

2. To track user's location and show the scale bar, you can use the properties `ShowsScale`, `ShowsUserLocation`, `UserTrackingMode` of `MGLMapView`. You may find [this tutorial](https://docs.mapbox.com/ios/maps/examples/user-tracking-mode/) helpful.

To simulate user's location & movement in an iPhone simulator, please check [this article](https://blog.pieeatingninjas.be/2017/02/10/custom-location-and-movement-on-xamarin-remoted-ios-simulator-for-windows/)

3. Please check if the current map's zoom level satisfy the zoom range of the text field.

**Comment by raimondslinde** [comment]
Hi @fleuverouge 

You are right about MGLMapView. In my case the project is cross-platform MVVM Xamarin.Forms .NET Standard Library and MapView is created on XAML from `xmlns:map="clr-namespace:Naxam.Controls.Forms;assembly=Naxam.Mapbox.Forms"`. Do you know if I need to convert to Xamarin.Classic iOS project or I can continue and use DependencyService? I know I can implement platform specific code using DependencyService, but In my case I just need to create a new mapView 
`public MGLMapView GetIOSMapView()
        {
            var mapView = new Mapbox.MGLMapView
            {
                ShowsScale = true,
                ShowsUserLocation = true,
                ShowsUserHeadingIndicator = true,
            };
            return mapView;
        }`
And all my code/logic is behind .NET Standard Library and `Naxam.Mapbox.Forms` is outdated.

Again thank you for your time.

**Comment by raimondsL** [comment]
ITMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:
@rpath/MapboxMobileEvents.framework/MapboxMobileEvents

**Comment by yauhenipakala** [comment]
Hi
We published v6.2.1 into the NuGet. Works fine in production.
https://www.nuget.org/packages/Softeq.Mapbox.iOS

**Comment by tuyen-vuduc** [comment]
@wcoder ,

It'll be great if you could create a PR to this repo, so there won't be many duplication on Nuget.org.

Regards.

**Comment by tuyen-vuduc** [comment]
Guys, please check out the latest binding [here](https://github.com/NAXAM/mapbox-ios-binding/tree/v10.5.0).
