### ISSUE TITLE
Polyline WithCoordinates is not receiving an array.

### ISSUE THREAD

**Issue by sillerjp** [NAXAM/mapbox-ios-binding#4]
MGLPolyline withcoordinates should have IntPtr instead of CLLocationCoordinate2D since C# will treat it as a single variable instead of an array.

**Comment by tuyen-vuduc** [comment]
Plz check out latest update if it's still there.

**Comment by sergsel** [comment]
One way to create MGLPolyline is use PolylineWithCoordinates that accepts NSArray. Could you post the code example to cast the array CLLocationCoordinate2D[] to NSArray or another working code? Next code from mapbox-xamarin-forms seems does not work:

        MGLPolyline PolyLineWithCoordinates (Position[] positions)
        {
            if (positions == null || positions.Length == 0) {
                return null;
            }
            var first = positions[0].ToCLCoordinate();
            var output = MGLPolyline.PolylineWithCoordinates (ref first, 1);
            var i = 1;
            while (i < positions.Length) {
                var coord = positions[i].ToCLCoordinate();
                output.AppendCoordinates (ref coord, 1);
                i++;
            }
            return output;
}

**Comment by tuyen-vuduc** [comment]
Here you are, @sergsel.

```
NSValue *aValue = [NSValue valueWithMKCoordinate:_userLocation];
```
For value type, we must use `NSValue` to wrap.

https://stackoverflow.com/questions/24926718/sending-cllocationcoordinate2d-to-parameter-of-incompatible-type-my-code-in-xcod

**Comment by sergsel** [comment]
I'm using next code xamarin:

            NSValue[] lineCoordsNSValue = new NSValue[lineCoords.Count];
            int i = 0;
            lineCoords.ForEach(x =>
            {
                lineCoordsNSValue[i] = NSValue.FromMKCoordinate(x);
                i++;
            });

            NSArray lineCoordsNSArray = NSArray.FromObjects(lineCoordsNSValue);

            MGLPolyline myPolyline = MGLPolyline.PolylineWithCoordinates(lineCoordsNSArray, lineCoordsNSArray.Count);
            MGLPolyline[] myPolyLines = new MGLPolyline[] {myPolyline};
            MGLMultiPolyline myMultiPolyline = MGLMultiPolyline.MultiPolylineWithPolylines(myPolyLines);

            MGLShapeSource routeLineShapeSource =
                new MGLShapeSource(
                    routeLineSourceId,
                    myMultiPolyline,
                    options);
            myStyle.AddSource(routeLineShapeSource);

But no effect. What is wrong?

**Comment by fleuverouge** [comment]
Hi @sergsel Sorry for the late reply.
Please update to our latest code and check the sample.

```
           var coordinates = new CLLocationCoordinate2D[] {
                new CLLocationCoordinate2D(latitude: 35, longitude: -25),
                new CLLocationCoordinate2D(latitude: 20, longitude: -30),
                new CLLocationCoordinate2D(latitude: 0, longitude: -25),
                new CLLocationCoordinate2D(latitude: -15, longitude: 0),
                new CLLocationCoordinate2D(latitude: -45, longitude: 10),
                new CLLocationCoordinate2D(latitude: -45, longitude: 40)
            };
            var polyline = MGLPolyline.PolylineWithCoordinates(ref coordinates[0], (nuint)coordinates.Length);
            mapView.AddAnnotation(polyline);
```

**Comment by sergsel** [comment]
Thanks for reply fleuverouge, but your code still does not work.
coordinates[0] is underlined with "Argument 1 may not be passed with 'ref' keyword"

**Comment by sillerjp** [comment]
Hi,

I had the same issue, the binding as it is will not work. You need to modify the binding project to receive a IntPtr for that function “withCoordinates” then in an addition file have a function to handle it. The binding as it is won’t work for that function, I can add the fix to this project if it is okay with the author.

**Comment by tuyen-vuduc** [comment]
We currently use this lib in production, no issue. No need to use IntPtr in this case. Plz check it carefully.

**Comment by sillerjp** [comment]
Sounds good, I could not find the way either I had the same ref issue but I understand if you need to implement it some other way. Let me know if you want me to share the logic I used though.

**Comment by fleuverouge** [comment]
Hi @sergsel , @JPSiller Have you tried to build our demo project? Please use nuget package version 3.7.3.1, or add reference directly to the Naxam.Mapbox.iOS project.

**Comment by sillerjp** [comment]
Hi @fleuverouge 
Yes, I'm actually extending the functionality to fit my project needs. This project was really helpful. In my case it was easier to use a pointer and add a new function in an additions file but I see how wrapping it in NSValue would also work. 

Thanks

**Comment by tuyen-vuduc** [comment]
@JPSiller If you found any enhancement to include in the project, plz submit a pull request. We are willing to check and merge if it is ok.

BTW, the way to use of IntPtr isn't that very natural in C#. With @fleuverouge's way, you could just need to part the `ref` of first item in the C# array, thing will work in the way from Mapbox document.

I would like to close this issue.
