### ISSUE TITLE
Apply a MGLCircleStyleLayer to a cluster not work

### ISSUE THREAD

**Issue by ghost** [NAXAM/mapbox-ios-binding#5]
Hi,
I read this example in the mapbox official page 
https://www.mapbox.com/ios-sdk/examples/clustering
I translated it in c#. It works except for association between  the MGLSymbolStyleLayer, MGLCircleStyleLayer and the "cluster" component draw on the map. So, in the map the point are clustered, but not rendered with the correct style.

I do not know if this is a bug in the porting or another problem.
I guess the problem is the definition of NSPredicate. In the example is declared as

`"circlesLayer.predicate = NSPredicate(format: "%K == YES", "cluster")"`

in c#

`"Predicate = NSPredicate.FromFormat("%K == YES", new NSString("cluster"))"`

Can you check this problem?

**Comment by fleuverouge** [comment]
Hi @lfongaroScp , 
Sorry for the late response.
If you still have the problem, please [check out my code ](https://pastebin.com/MCvJLtRd) (just a pure conversion from Mapbox's tutorial to C#). It works as expected.
