### ISSUE TITLE
Publish version 3.7.3.2 to NuGet

### ISSUE THREAD

**Issue by dmitry-lt** [NAXAM/mapbox-ios-binding#6]
Please publish version 3.7.3.2 to NuGet

**Comment by tuyen-vuduc** [comment]
@dmitry-lt Have you update the binding library to v3.7.3.2?

**Comment by dmitry-lt** [comment]
3.7.3.2 package is in git: https://github.com/NAXAM/mapbox-ios-binding/blob/master/Naxam.Mapbox.iOS.3.7.3.2.nupkg, but it is not available on NuGet. The latest version is 3.7.3.1: https://www.nuget.org/packages/Naxam.Mapbox.iOS/3.7.3.1

I can install it from the file, but it would be much more convenient to install it from NuGet

**Comment by tuyen-vuduc** [comment]
Thank you for pointing out. Don't know that the version isn't published yet.

**Comment by tuyen-vuduc** [comment]
It should be there in few minutes.

Cheers.
